language: c
compiler:
    - gcc

addons:
  hosts:
    - ci.travis

env:
  global:
    - MERCURY_BUILD_CONFIGURATION="Debug"
    - MERCURY_DASHBOARD_MODEL="Continuous"
    - MERCURY_NO_LOOP="true"
    - MERCURY_DO_COVERAGE="false"
    - MERCURY_DO_MEMCHECK="false"
    - MERCURY_PORT_NAME='tcp://localhost:3344'
  matrix:
    - MPI=mpich

branches:
  only:
    - master

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y mpich2 libmpich2-3 libmpich2-dev

install:
    - ./Testing/travis_build.sh

script:
    - ctest -VV --output-on-failure -S ./Testing/travis_script.cmake

