language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

sudo: false
dist: trusty
group: beta

cache:
  directories:
    - $HOME/install

env:
  global:
    - MERCURY_DASHBOARD_MODEL="Continuous"
    - MERCURY_NO_LOOP="true"
    - MERCURY_PORT_NAME='tcp://localhost:3344'
  matrix:
    - MERCURY_BUILD_CONFIGURATION="Debug"
    - MERCURY_BUILD_CONFIGURATION="RelWithDebInfo"
    - MERCURY_BUILD_CONFIGURATION="Release"
    - MERCURY_MEMORYCHECK_TYPE="ThreadSanitizer"
    - MERCURY_MEMORYCHECK_TYPE="AddressSanitizer"

matrix:
  exclude:
   - os: osx
     env: MERCURY_MEMORYCHECK_TYPE="ThreadSanitizer"
   - os: linux
     env: MERCURY_MEMORYCHECK_TYPE="ThreadSanitizer"
     compiler: clang
   - os: osx
     env: MERCURY_MEMORYCHECK_TYPE="AddressSanitizer"
   - os: linux
     env: MERCURY_MEMORYCHECK_TYPE="AddressSanitizer"
     compiler: clang

branches:
  only:
    - master
    - topic_travis
    - travis_cron

before_install:
    - echo "Existing directories in $HOME" && ls $HOME
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpich; fi

install:
    - ./Testing/script/travis_build.sh

before_script:
    - ls $HOME/install/bin
    - export PATH=$HOME/install/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/install/lib:$HOME/install/lib64:$LD_LIBRARY_PATH
    - $CC --version
    - ctest --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/sys/kernel/yama/ptrace_scope; fi

script:
    - ctest -VV --output-on-failure -S ./Testing/script/travis_script.cmake

